/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup BootstrapGroup;
extern const Sifteo::AssetImage LoadingBg;
extern const Sifteo::AssetImage Loading;
extern Sifteo::AssetGroup MenuGroup;
extern const Sifteo::AssetImage Tip2;
extern const Sifteo::PinnedAssetImage BgTile;
extern const Sifteo::PinnedAssetImage StripeTile;
extern const Sifteo::AssetImage Label1;
extern const Sifteo::PinnedAssetImage menubg;
extern const Sifteo::AssetImage Icon1;
extern const Sifteo::AssetImage Icon8;
extern const Sifteo::AssetImage Icon2;
extern const Sifteo::AssetImage Icon3;
extern const Sifteo::AssetImage Icon4;
extern const Sifteo::AssetImage Icon5;
extern const Sifteo::AssetImage Icon6;
extern const Sifteo::AssetImage Icon7;
extern const Sifteo::AssetImage Icon9;
extern const Sifteo::AssetImage Tip1;
extern const Sifteo::AssetImage Footer;
extern const Sifteo::AssetImage Label2;
extern const Sifteo::AssetImage Label3;
extern const Sifteo::AssetImage Label4;
extern const Sifteo::AssetImage Label5;
extern const Sifteo::AssetImage Label6;
extern const Sifteo::AssetImage Label7;
extern const Sifteo::AssetImage Label8;
extern const Sifteo::AssetImage Label9;
extern const Sifteo::AssetImage Label10;
extern Sifteo::AssetGroup Menu1Group;
extern const Sifteo::PinnedAssetImage testBG;
extern const Sifteo::PinnedAssetImage Menu1menubg;
extern const Sifteo::AssetImage Menu1Icon1;
extern const Sifteo::PinnedAssetImage Menu1BgTile;
extern const Sifteo::PinnedAssetImage Menu1StripeTile;
extern const Sifteo::AssetImage Menu1Icon2;
extern const Sifteo::AssetImage Menu1Icon3;
extern const Sifteo::AssetImage Menu1Icon4;
extern const Sifteo::AssetImage Menu1Icon5;
extern const Sifteo::AssetImage Menu1Tip1;
extern const Sifteo::AssetImage Menu1Tip2;
extern const Sifteo::AssetImage Menu1Footer;
extern const Sifteo::AssetImage Menu1Label1;
extern const Sifteo::AssetImage Menu1Label2;
extern const Sifteo::AssetImage Menu1Label3;
extern const Sifteo::AssetImage Menu1Label4;
extern const Sifteo::AssetImage Menu1Label5;
extern const Sifteo::AssetImage Menu1Label6;
extern Sifteo::AssetGroup CourseGroup;
extern const Sifteo::AssetImage e;
extern const Sifteo::AssetImage a;
extern const Sifteo::AssetImage b;
extern const Sifteo::AssetImage c;
extern const Sifteo::AssetImage d;
extern const Sifteo::AssetImage f;
extern const Sifteo::AssetImage g;
extern const Sifteo::AssetImage h;
extern const Sifteo::PinnedAssetImage Loadingmove[14];
